### ISSUE TITLE
Store Tokens in a database and recreate them for later uses

### ISSUE THREAD

**Issue by jingw222** [felix-hilden/tekore#135]
Hey, this might be a pretty silly question. :]
So basically I want to save `Token` objects into a static database and then retrieve them into memory sometime in future. Should I just put all the attributes of a `Token` as plain texts into fields of a table, and recreate it with `Token(**attr)`? Or something proper or more convenient I'm not aware of? Pickling? Any security concerns involved in the process?

**Comment by felix-hilden** [comment]
Hey, I believe our documentation might have an answer [here](https://tekore.readthedocs.io/en/stable/documents/advanced_usage.html#token-persistence). Let me know if you have more questions!

**Comment by jingw222** [comment]
Does that mean the backend needs to load the refresh token from the database in order to get a user token every time it makes a request? I was asking this because when I store the `Token` in a global dictionary and get it there, it wouldn't work if the server app spawns multiple workers, the global variable is not shared in memory across processes.

**Comment by HarrySky** [comment]
You can try Redis for sharing state between workers it can act as both `key-value` storage and `message broker`. Easiest way is to just store it in file (given your workers share the same filesystem)

**Comment by jingw222** [comment]
Thank you for your kind help! Redis is obviously a solid approach. But for a small project I just don't bother to setup a Redis server for now. Storing it in files seems more expedient. What if I store the user token object in a server-side session filesystem storage? Would it work as expected?

**Comment by felix-hilden** [comment]
Redis is a neat tool, or you could even store the tokens in memory for their duration. Bothering the DB once an hour doesn't seem too much. At least to my knowledge multiple tokens can be active simultaneously.

**Comment by jingw222** [comment]
Thanks, your solution sounds viable, but considering my limited experience with sharing data between processes, it might be a recipe for debugging headaches. So my current makeshift is to store the transient `Token` in server-side session file storage, and `refresh_token` in a separate database like you said. It seems to work and I was kinda a little surprised there's no serialization or pickling needed at all.
