### ISSUE TITLE
Questions surrounding RefreshingCredentials

### ISSUE THREAD

**Issue by Because789** [felix-hilden/tekore#137]
Hi Felix, first of all thanks a lot for all the work you put into this project! I'm working on a Flask web app and I'm having a great time playing around with your tool. This is my very first Python project and therefore I have a lot to learn. So far I was able to solve most of my problems, but there are a few things I just can't wrap my head around.

1. I used https://tekore.readthedocs.io/en/latest/examples/auth_server.html to get things started (but with RefreshingCredentials to get the creds). In the callback route I want to add the user with his tokens into a database. Now, as far as I understand, RefreshingToken inherits the __str__ method from AccessToken, therefore, when I pass a RefreshingToken object into a function, I pass an access token string and I don't have access to the properties of the object anymore. To illustrate, here is the relevant part of the callback route:

```
code = request.args.get('code', None)
token = cred.request_user_token(code)

with spotify.token_as(token):
    info = spotify.current_user()

# This works:
access_token=token.access_token,
refresh_token=token.refresh_token,

def add_user_to_db(info, access_token, refresh_token):
	add_user = PremiumUser(
        spotify_id=info.id,
        spotify_username=info.display_name,
        access_token=access_token,
        refresh_token=refresh_token,
    )

add_user_to_db(info, access_token, refresh_token)

# I'd like to do it this way, but it doesn't work:
def add_user_to_db(info, token):
	add_user = PremiumUser(
        spotify_id=info.id,
        spotify_username=info.display_name,
        access_token=token.access_token,
        refresh_token=token.refresh_token,
    )

add_user_to_db(info, token)
```

Is there a way to pass a RefreshingToken object into a function and still have access to its properties? I know this is mainly cosmetic (and a bit less code), but it still bothers me :)

2. Another thing about RefreshingToken is still unclear to me. I implemented my app as an app factory and with blueprints. As I understand it, the token object created in the callback route has to be persistent to actually make the refreshing work automatically. How can this be accomplished when the request_user_token is called from within a route?

3. Am I right, that since I put the access token in a database and retrieve it from there, there is actually no benefit at all in using RefreshingToken? Which means, in my case I have to implement a routine to check if a token is about to expire myself? And is it right, that I still benefit from using RefreshingCredentials, because it refreshes the client token automatically (I use PersistentSender)?

I'm sorry about my noob questions, but some enlightenment would be much appreciated!

**Comment by felix-hilden** [comment]
Hi! Thank you for your kind words.

1. There should be no problem with passing token objects around. Only when `str(token)` is called (e.g. in the Spotify client just before sending requests), the object is converted to its access token string. The properties should be available everywhere. So maybe you are doing something odd with it. Or we have a bug here. Could you provide some more information?

2. Any method of getting your token outside the callback function scope will do. In the example I have used a global dictionary which is updated on login. You could also just use a global Spotify instance and set its token, if you only have one user.

3. This depends on what you're doing with it. If you are storing the whole token (which is maybe [not advisable](https://tekore.readthedocs.io/en/stable/documents/advanced_usage.html#token-persistence)) then I would use regular, expiring tokens. But if you are planning on having the token around in memory for a long time (to not bother the db as much), then might as well use the refreshing variant. See the discussion in #135 for more details.

Did I answer your concerns?

**Comment by felix-hilden** [comment]
You know, now that I think about it, the server example does lack *using* the token for something. Now it's simply discarded after authentication. We should improve it.

**Comment by felix-hilden** [comment]
I fixed it just now, the change can be seen after the next release or in the development documentation [here](https://tekore.readthedocs.io/en/latest/) (though it seems that RTD has some build issues currently).

**Comment by Because789** [comment]
Thanks a lot for your quick reply!

1. Well what can I say, I just tried again and of course it did work as expected. I tried to pass the object around in the past and it didn't work, so I'm sure I did something odd back then. Forgive my brain fart.

2. and 3. are basically also answered with your quick fix in the documentation and with what you provided before. Thanks a lot for your help!
