### ISSUE TITLE
Handling of throttled Spotify API calls

### ISSUE THREAD

**Issue by alexpogue** [felix-hilden/tekore#142]
Hey Felix, thanks for the amazing library! Looks tons better than the old spotipy repo. Glad you took this over!

I found a possible issue - I get an error when `fields` parameter is specified for `playlist(...)`. I would expect the function to return either a `playlist` or an `object` depending on whether fields is specified (similar to the behavior of `playlist_tracks(...)` at https://github.com/felix-hilden/tekore/blob/master/tekore/client/api/playlist/view.py#L117), but instead it appears to only ever return a `FullPlaylist` (see https://github.com/felix-hilden/tekore/blob/master/tekore/client/api/playlist/view.py#L73). Is there a reason you chose not to return a union of `playlist` and `object` for `playlist(...)`?

Thanks again, you're the best!

**Comment by felix-hilden** [comment]
Thank you for your kind words!

Yeah, that's clearly just an oversight on my part. It should be similar to the tracks call. I'll fix it right away.

**Comment by felix-hilden** [comment]
Expect this to ship with the next release!

**Comment by felix-hilden** [comment]
And to clarify the references, somewhat embarrassingly I had to redo the commit twice. So the latest reference is valid. I'm still not quite accustomed to properly making release notes with each commit.
