### ISSUE TITLE
converting using from_url does not allow for https:// urls

### ISSUE THREAD

**Issue by MyNameBeMrRandom** [felix-hilden/tekore#165]
As the title says, when using `tekore.convert.from_url` it does not allow for http urls which are what the spotify client and web player both give when copying songs urls. Is there a reason for this?

**Comment by felix-hilden** [comment]
Thanks for posting! If this is indeed the case, then no reason. I'll see if the return urls should change too. But the API docs at https://developer.spotify.com/documentation/web-api/ still mention http urls only. So let's also figure out if both are used and where.

**Comment by MyNameBeMrRandom** [comment]
As above, spotify gives me a https url when using the copy url feature of both the web player and the desktop app, these urls work just fine and even the normal http urls redirect to a https one.

**Comment by felix-hilden** [comment]
I do believe you, but I'll verify things myself too. Good to know about the redirects.

**Comment by felix-hilden** [comment]
Yeah, let's add the `https` style prefix to the list of accepted ones. Also, we'll return `https` URLs in `to_url` as well, since they seem to be used quite exclusively by Spotify.
