### ISSUE TITLE
Support httpx 0.12.*

### ISSUE THREAD

**Issue by marioortizmanero** [felix-hilden/tekore#166]
Hi there Felix,

Are you planning on bumping httpx to `0.12.*`? This module restricts its version to `0.11.*`, which is a problem on Arch Linux because it already only has `0.12.1` available right now. This isn't an issue that should concern you, but I wanted to know if it's worth creating another package for previous httpx versions on the AUR.

Here's the changelog - https://github.com/encode/httpx/blob/master/CHANGELOG.md

Thanks!

**Comment by marioortizmanero** [comment]
> And then let's hope for the 1.0 release soon. But I'm somewhat pessimistic given the current state of the world.

I would expect more open source activity these days now that everyone's at home! :laughing: 

> Damn AUR is fast to abandon old versions of packages. What's your ordinary protocol of dealing with dependencies to old versions? Do they exist for other packages or do you install via pip or something? Just curious.

Yeah the AUR usually doesn't take less than a week to update packages. Old versions are just normal packages with the version in the name. For example, Qt 4 is available at [qt4](https://aur.archlinux.org/packages/qt4/). They're not really common, though.

By the way, GitHub has [dependency tracker bots](https://github.com/marketplace/dependabot-preview) that can automatically open an issue when a dependency is outdated. Not sure if it's worth it for you, but you might want to take a look :)

**Comment by felix-hilden** [comment]
Yeah, that could be useful! I'll have a go.

**Comment by felix-hilden** [comment]
@marioortizmanero A new version with `httpx>=0.11,<0.13` is now published and ready for AUR as well!
