### ISSUE TITLE
Help with recommendations

### ISSUE THREAD

**Issue by jward8** [felix-hilden/tekore#172]
Hi, I'm fairly new to using tekore and I keep on getting a 401 response message when trying to call the recommendations method.
`id_list = [track.id for track in track_list]
recommended = spotify.recommendations(track_ids=id_list).tracks`
Any suggestions? I've read over the docs and I'm still confused on what could be occuring

**Comment by felix-hilden** [comment]
Could you provide some more information so I can try to reproduce the situation? What is the full error message and what is inside `id_list`? My first guess is that the list exceeds the allowed amount of seed tracks which is 5.

**Comment by jward8** [comment]
`from tekore.util import request_client_token
from tekore import Spotify
from tekore.scope import read
from tekore.util import prompt_for_user_token
import tekore

client_id = # my client id 
client_secret = # my client secret id
redirect_uri = 'https://google.com/'

user_token = prompt_for_user_token(
    client_id,
    client_secret,
    redirect_uri,
    scope= read
)

app_token = request_client_token(client_id,client_secret)

spotify = Spotify(app_token)
spotify.token = user_token

track_list = []
for set in range(0,40,20):
    library = spotify.saved_tracks(None,limit=20,offset=set).items
    for track in library:
        track_item = track.track
        if track_item.popularity <= 40:
            track_list.append(track_item)

id_list = [track.id for track in track_list]
recommended = spotify.recommendations(track_ids=id_list).tracks
for track in recommended:
    print(track.name)`

This is what I have exactly

**Comment by felix-hilden** [comment]
For me this gives an error with code 400, which is because there are more seed tracks than the allowed 5. Could you provide the full error message you are getting?

Side note, tripling those backticks achieves the code formatting you are after. Then you can include indentation as well, making it easy to copy and it looks a lot better.

**Comment by jward8** [comment]
Ahh, I meant 400 instead of 401. My bad.

This is the message:
tekore.client.decor.error.BadRequest: Error in https://api.spotify.com/v1/recommendations?limit=20&seed_tracks=0WEEZBjQKBLwtjwHKXYj0z%2C7sEwg5LnC77gsi4JjjPQJ6%2C2K5l84PLB7qeLDzTWgSNFK%2C5jCJr48wz1MEu7HBUGl2IC%2C2FvpskTQMlonzaEcZIV9m2%2C3f8fgiq7LuCHdZhGYak99o%2C6npSUgBS9BcNTeoDoq4UFq%2C3VbVRFmYsqmtaeFo4RSXXe%2C5Cay62XkdMb6WGnDbNzdIx:
400: invalid request

**Comment by jward8** [comment]
I understand what I was doing now, thanks for the help!
