### ISSUE TITLE
PrivateUser has no birthdate attribute

### ISSUE THREAD

**Issue by kddlb** [felix-hilden/tekore#197]
### Issue
I get a `TypeError`: `__init__() got an unexpected keyword argument 'birthdate'` while getting a [PrivateUser](https://github.com/felix-hilden/tekore/blob/4d1d38a8c372c30aed74244fdf2af35e06251c12/tekore/_model/user.py#L38) through the `current_user()` method.

The keys of the JSON dict from the API call are
`dict_keys(['birthdate', 'country', 'display_name', 'email', 'explicit_content', 'external_urls', 'followers', 'href', 'id', 'images', 'product', 'type', 'uri'])`

### Expected behavior
I should've gotten a PrivateUser.

### Steps to reproduce
If applicable and possible, please provide a
[minimal working example](https://stackoverflow.com/help/minimal-reproducible-example).

```python
displayName = spotify.current_user().display_name
```

**Comment by felix-hilden** [comment]
Thank you for the report! However, I cannot reproduce this. I do have a birthdate set in my Spotify account. Do you have anything out of the ordinary going on either with your account or the token setup?

I do believe you of course, but I wonder why this would happen for only some.

**Comment by kddlb** [comment]
I removed the previous authorization.

These are the scopes: 
```python
authUrl = cred.user_authorisation_url(scope=[tk.scope.user_read_playback_state,
                                                         tk.scope.user_read_currently_playing,
                                                         tk.scope.user_modify_playback_state],
                                                  show_dialog=True)
```

And this is the Spotify authorization page:

![image](https://user-images.githubusercontent.com/115702/88776597-2ff0f500-d154-11ea-85d4-ab7db71328b0.png)

...I tried authorizing again, and it worked! But when I started my app again, it gave me the same error.

I set up a breakpoint [here](https://github.com/felix-hilden/tekore/blob/68c4827fa4f18cd0db7d27897a043018ebc03b08/tekore/_client/process.py#L25), and I see the keys of the JSON are as follows:
`dict_keys(['display_name', 'external_urls', 'followers', 'href', 'id', 'images', 'type', 'uri'])`

I think there's something funky with the refresh token, since I only store that, as recommended by the documentation, if I recall correctly.

**Comment by felix-hilden** [comment]
Interesting... That could be worth examining. I'll test this out later today as well. Let me know if you find anything! And by the way, thank you for the very detailed explanations, they are nice to read 👍

**Comment by felix-hilden** [comment]
@kddlb Also it seems that you are using an older version of the library, one that still had the `show_dialog` parameter. Would you mind upgrading to the newest version and see if the issue persists? I doubt that it makes any difference, but just to be extra sure.

**Comment by felix-hilden** [comment]
So the following works for me just fine:

```python
cid, csc, ruri = tk.config_from_environment()
token = tk.prompt_for_user_token(cid, csc, ruri, scope=[
    tk.scope.user_read_playback_state,
    tk.scope.user_read_currently_playing,
    tk.scope.user_modify_playback_state,
])

spotify = tk.Spotify(token)
print(spotify.current_user().display_name)
print(spotify.token.scope)

refreshed = tk.refresh_user_token(cid, csc, token.refresh_token)
spotify.token = refreshed
print(spotify.current_user().display_name)
print(spotify.token.scope)
```

But as you said, the token scope *is* expanded when refreshing! I have not been aware of this. But it seems logical given the use case of gradually expanding privileges. This allows to only store one refresh token instead of juggling multiple with various scopes. Even if the bug cannot be reproduced, this should 100 % be added to the documentation!

**Comment by kddlb** [comment]
I just tested with new client credentials, and you're right; refreshing didn't expand the scope of the token.

**Comment by felix-hilden** [comment]
Hmm.. Can you reproduce the situation at all with new credentials?

**Comment by felix-hilden** [comment]
@kddlb pinging to break this silence and hopefully get this issue a bit closer to being resolved. Any news?

**Comment by kddlb** [comment]
I don't understand what you mean by "new credentials"... I tried with new app credentials; and I don't have access to another Spotify account.

**Comment by felix-hilden** [comment]
I meant the new client credentials you mentioned earlier. Can you reproduce the situation reliably? You said that it didn't work when you used your app, which obviously cannot have anything to do with it.

**Comment by felix-hilden** [comment]
If there's nothing that can reproduce the bug, I'll close this issue because of the lack of information for housekeeping. But I'll mark it for tracking in case the situation develops. Feel free to provide more information if you have any, @kddlb.

**Comment by felix-hilden** [comment]
Actually, this was reported already in #52, which was closed without changes. Given these two instances already we ought to make the change even if it can't be reproduced. Apparently (from the previous issue) it has something to do with a birthday scope that is no longer valid, but present in some tokens.
