### ISSUE TITLE
Error on retrieving playback when a local file is playing

### ISSUE THREAD

**Issue by Allerter** [felix-hilden/tekore#200]
### Issue
If I try to get the user's playback using `playback()` or `playback_currently_playing()`, and the useris playing a local file at that moment, I get the following error:
`TypeError: __init__() missing 1 required positional argument: 'total_tracks' `

### Expected behavior
If the user is playing a local file, the fetched result should contain the track's name and artist, but the album should be empty.

### Steps to reproduce
```python
cred = tk.RefreshingCredentials(SPOTIFY_CLIENT_ID,
                                SPOITFY_CLIENT_SECRET)
token = cred.refresh_user_token(SPOTIFY_REFRESH_TOKEN)
spotify = tk.Spotify(token)
spotify.playback_currently_playing()  # or spotify.playback()
```

**Comment by felix-hilden** [comment]
Thank you for the report! Since it's a local track, it might be better off with similar "empty" artists as other members already are. Not sure yet. I'll take a look tomorrow and get back to you!

**Comment by Allerter** [comment]
Manually requesting the playback returned the following result for a local file:
```python
{
  "timestamp" : 1596383702885,
  "context" : null,
  "progress_ms" : 2270,
  "item" : {
    "album" : {
      "album_type" : null,
      "artists" : [ ],
      "available_markets" : [ ],
      "external_urls" : { },
      "href" : null,
      "id" : null,
      "images" : [ ],
      "name" : "Manic (Deluxe)",
      "release_date" : null,
      "release_date_precision" : null,
      "type" : "album",
      "uri" : null
    },
    "artists" : [ {
      "external_urls" : { },
      "href" : null,
      "id" : null,
      "name" : "Halsey",
      "type" : "artist",
      "uri" : null
    } ],
    "available_markets" : [ ],
    "disc_number" : 0,
    "duration_ms" : 174000,
    "explicit" : false,
    "external_ids" : { },
    "external_urls" : { },
    "href" : null,
    "id" : null,
    "is_local" : true,
    "name" : "929",
    "popularity" : 0,
    "preview_url" : null,
    "track_number" : 0,
    "type" : "track",
    "uri" : "spotify:local:Halsey:Manic+%28Deluxe%29:929:174"
  },
  "currently_playing_type" : "track",
  "actions" : {
    "disallows" : {
      "pausing" : true,
      "skipping_prev" : true
    }
  },
  "is_playing" : false
}
```
Although many of the files are empty and have no data, `item.artist[0].name`, `item.name` and `item.album.name` (as they'd be accessed using Tekore) are provided, and could be useful (for example Discord displays any of the three fields I mentioned if they are present). And whenever those fields weren't present, the request returned an empty string for their value.

**Comment by felix-hilden** [comment]
Thanks a lot! This info helps a ton already :smile:

**Comment by felix-hilden** [comment]
Okay, so most likely we'll need to introduce similar "local" versions of objects to playback endpoints as we have for playlist items already. I managed to parse the response using the same `LocalTrack` as we already have, but I'll validate and test more thouroughly, we could even manage to make the very loose None attributes a bit more strict overall.

**Comment by felix-hilden** [comment]
Our test coverage will take a hit, as we have no way of testing this automatically by starting playback of a local track. But I'm A-OK with that. Also turns out that the local objects are already quite strict meaning they don't allow any missing attributes. So we're good to go.

**Comment by felix-hilden** [comment]
@Allerter This fix is now released with the new version!
