### ISSUE TITLE
Argument validation

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/tekore#206]
Tekore uses type hints and descriptive names. Usability could be taken to the next level, however, by validating function arguments. So far there has been no validation, but it is definitely an option. I see several approaches.
- No changes: easy and acceptable
- Lazy validation: validate arguments that could be confused, like is `uris` actually a list like it's supposed to be, or a string (for a single uri) instead
- Light validation: validate top-level argument types
- Heavy validation: validate all parameters to the best of our abilities, e.g. `uris` would have to contain valid Spotify URIs to pass the check

I think heavy validation is too much. Spotify already provides error responses when something goes wrong. But by validating a little we could provide better error messages ourselves where we can. Thoughts?

**Comment by HarrySky** [comment]
I think we can also use `@overload` decorator from `typing` module. I had an idea with this decorator and improving type suggestions when using `await`, but I don't have time for this at the moment 🙈

**Comment by felix-hilden** [comment]
Oh, I didn't know about that, cool! But it seems that it is for type hinting rather than runtime checks to validate that an argument is really the type the API needs. What did you mean?

**Comment by HarrySky** [comment]
I meant type hinting, so that VS Code will show me types

**Comment by felix-hilden** [comment]
Fair enough, if you see a need for it, I'm open for suggestions! But I think that calls for another issue. Let's keep this one for validation.

**Comment by jingw222** [comment]
Is [pydantic](https://pydantic-docs.helpmanual.io/) what you need? FastAPI uses it extensively for data validation and error handling afaik.

**Comment by felix-hilden** [comment]
Hmm, at first glance that looks promising! I'll take a closer look later. Thanks!

**Comment by oroddlokken** [comment]
[recommendations()](https://github.com/felix-hilden/tekore/blob/master/tekore/_client/api/browse/__init__.py#L188) might be one of those functions who could make use of some additional client side validation. The [endpoint](https://developer.spotify.com/documentation/web-api/reference/browse/get-recommendations/) requires at least one of the artist_ids, genres or track_ids parameters to be defined when calling it, otherwise it returns a "invalid request" error.

**Comment by felix-hilden** [comment]
Thanks 👍 Yeah I think the heavy validation we discussed earlier is too much, but this kind of validation could be okay. I think we'll have to see exactly where it is appropriate. For example in the recommendation case receiving "invalid request" is ambiguous, when we could easily check and inform "at least one seed has to be given" or something. But if the API actually returns helpful messages we should not try to do it ourselves.

This leads to the question: which error classes should we raise? We could have something like `InvalidArgumentError`, but because we cannot check all arguments, raising the HTTP error that *would* be raised without actually sending requests could actually be appropriate. But it might also be confusing. Also, another error class would be a breaking change.

If we find no other places where we'd like to check arguments, I'm tempted to leave it to good documentation. But let's see.

Thoughts?

**Comment by felix-hilden** [comment]
I think after changing the documentation for recommendations, there is no acute need for argument validation, and I don't see a major benefit when compared to the difficulty of implementing it. So I'll close this for the time being.
