### ISSUE TITLE
httpx.ConnectTimeout

### ISSUE THREAD

**Issue by jingw222** [felix-hilden/tekore#215]
Most of the time, everything looks pretty good. But this `httpx.ConnectTimeout` happens occasionally. I wonder if this has anything to do with my `sender` setup though. 

```
  File "/usr/local/lib/python3.7/site-packages/tekore/_sender/client.py", line 78, in wrapper
    response = self.send(request)
  File "/usr/local/lib/python3.7/site-packages/tekore/_client/base.py", line 70, in send
    return self.sender.send(request)
  File "/usr/local/lib/python3.7/site-packages/tekore/_sender/extending.py", line 297, in send
    fresh = self.sender.send(request)
  File "/usr/local/lib/python3.7/site-packages/tekore/_sender/extending.py", line 86, in send
    r = self.sender.send(request)
  File "/usr/local/lib/python3.7/site-packages/tekore/_sender/concrete.py", line 41, in send
    data=request.data,
  File "/usr/local/lib/python3.7/site-packages/httpx/_client.py", line 674, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/httpx/_client.py", line 704, in send
    request, auth=auth, timeout=timeout, allow_redirects=allow_redirects
  File "/usr/local/lib/python3.7/site-packages/httpx/_client.py", line 733, in _send_handling_redirects
    request, auth=auth, timeout=timeout, history=history
  File "/usr/local/lib/python3.7/site-packages/httpx/_client.py", line 769, in _send_handling_auth
    response = self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.7/site-packages/httpx/_client.py", line 803, in _send_single_request
    timeout=timeout.as_dict(),
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/httpx/_exceptions.py", line 359, in map_exceptions
    raise mapped_exc(message, **kwargs) from exc  # type: ignore
httpx.ConnectTimeout: The handshake operation timed out
```

For reference, here's the sender that I'm using.
```python
sender = tk.CachingSender(max_size=256, sender=tk.RetryingSender(retries=3))
app_token = cred.request_client_token()
spotify = tk.Spotify(token=app_token, sender=sender)
```
Anything suspicious?

**Comment by felix-hilden** [comment]
Hi! I haven't experienced any connection timeouts, either locally or in CI tests. Additionally, caching and retrying senders do not make connections themselves. This leads me to believe it is a legit connection timeout, which we can of course do nothing about. And I think letting HTTPX raise in this case is appropriate. Some clarifications:

- Do you have reason to doubt your internet connection?
- Have you set HTTPX options for timeouts?
- Does this occur in a specific endpoint or randomly?

**Comment by jingw222** [comment]
> Hi! I haven't experienced any connection timeouts, either locally or in CI tests. Additionally, caching and retrying senders do not make connections themselves. This leads me to believe it is a legit connection timeout, which we can of course do nothing about. And I think letting HTTPX raise in this case is appropriate. Some clarifications:
> 
> - Do you have reason to doubt your internet connection?
> - Have you set HTTPX options for timeouts?
> - Does this occur in a specific endpoint or randomly?

Thanks for your prompt reply and suggestions. 

My network connection is decent, there could a few random hiccups that I was not aware of though. I didn't configurate custom setups for HTTPX, and this happened pretty randomly accross many endpoints.

So I'll check some other solutions and possibly file the issue to HTTPX.

**Comment by felix-hilden** [comment]
Alright, this sounds more and more like it is not a Tekore issue then. But you could try raising the HTTPX timeout values (5 sec by default which could be short) and see if that helps. I'll close the issue for the time being. But do reply if new information comes to light!

**Comment by alexpogue** [comment]
I faced this same issue and increasing the timeout seemed to fix the issue:

```
    # increase the timeout to prevent spotify timeouts
    big_timeout_client = httpx.Client(timeout=60.0)
    big_timeout_sender = SyncSender(big_timeout_client)

    return Spotify(app_token, sender=big_timeout_sender)
```

I did have to dig a while to find this Github issue and the resolution steps. I wonder if having it in the documentation or examples somewhere would make it more visible to newcomers.

**Comment by felix-hilden** [comment]
Yeah this could very well be added to the documentation!

**Comment by Pfed-prog** [comment]
cheers, timeout=60.0 solved similar issue that I faced with parsing hh.ru .
