### ISSUE TITLE
Logo on non-white backgrounds

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/tekore#235]
Since GitHub has introduced the dark theme, I noticed (remembered) that our logo is transparent in all the wrong ways. There's an ugly grayish border on the picture, and the logo isn't very visible from the dark blue background. Maybe we ought to update it a bit.

I'm thinking about three variations:
- Make a white box around the logo, to bring it back to original
- Remove the gray and maybe replace it with transparency
- Make a white (or off-white) outline of some thickness, maybe with a fade to transparency

Let's test out each one.

**Comment by felix-hilden** [comment]
The white box most likely won't do, because it increases the logo size and could look ugly in headings:
![logobox](https://user-images.githubusercontent.com/25202257/104134136-85caf980-5390-11eb-878b-9b624c3df970.png)

**Comment by felix-hilden** [comment]
A bit of white gaussian blur as an outline is most likely the way to go. But as I'm editing the logo I noticed that there are some other artifacts as well, likely from the Spotify logo edit and transparency brushing. So let's make it clean this time.

**Comment by felix-hilden** [comment]
One custom paint.net plugin later I managed to do it 😅 Here's two different widths of blur. They of course are invisible on white backgrounds.

![logo-tight](https://user-images.githubusercontent.com/25202257/104137818-4f997400-53a8-11eb-9844-020f9653cc14.png)
![logo-wide](https://user-images.githubusercontent.com/25202257/104137821-51fbce00-53a8-11eb-9090-f640fda47d62.png)

Thoughts?

**Comment by HarrySky** [comment]
@felix-hilden first looks better to me :smile:

**Comment by felix-hilden** [comment]
Thanks for the comment! I think we'll go with that one. The small variant of the logo looks quite bad with any other zoom than exactly 1:1 since the blur is only one pixel, but we'll deal with it.

**Comment by felix-hilden** [comment]
Here's what it looks like in readme. Maybe a little too much outline, I'm not sure.

![logoexample](https://user-images.githubusercontent.com/25202257/104171060-bb142d80-540a-11eb-8023-ca005cf9d2d4.png)
