### ISSUE TITLE
Implement async functionality in separate classes

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/tekore#240]
From #221: Earlier I made a design choice of implementing both sync and async functionality in the same class and same methods using a boolean toggle in the `Spotify` class constructor. This was done for two reasons: it is easier to maintain API code with minimal duplication since it abstracts the sync-async handling away into one function (decorator), it is dead simple to use - just pass an argument and start awaiting.

But in the linked issue, which dealt with type hinting, we failed to figure out a way to provide correct static type hints using the same methods for both sync and async. A discussion should therefore be had about whether or not we should change the implementation to use dedicated classes for each. Its obvious upside would be that we could finally provide *correct* type hints, the downsides being mostly effort and a breaking change in the library. Once the work is done, maintenance shouldn't be *that* big of an issue.

Personally I'm not yet convinced that we absolutely need the separate async class, but I'm open for possibilities. This change would be the first to need a major version number bump to 4.0, so we're not in a hurry. Thoughts?

**Comment by felix-hilden** [comment]
Unless there are major advantages to having the type hints be correct (beyond a few IDE/mypy complaints), I'm inclined to let this issue be. I don't see the value outweighing the increased maintenance difficulty.

**Comment by HarrySky** [comment]
Yeah, totally agree, that maintenance cost outweighs in this case. I, for example, can still use it, but with `# type: ignore` or other workarounds. But proper type annotations are good for Developer Experience.

Haven't used tekore in a while, though, not much time for personal projects :smile:
