### ISSUE TITLE
Invalid / illegal URI

### ISSUE THREAD

**Issue by Abdulsamipy** [felix-hilden/tekore#268]
trying to play a track but it is giving invalid URI

### Issue
KeyError: 'Passed URL contains no parameter `code`!'

### Steps to reproduce

import tekore as tk

client_id = "id"
client_secret = "sec"
redirect_uri = "spotify:track:52xJxFP6TqMuO4Yt0eOkMz"

conf = (client_id, client_secret, redirect_uri)
token = tk.prompt_for_user_token(*conf, scope=tk.scope.every)

spotify = tk.Spotify(token)
tracks = spotify.current_user_top_tracks(limit=10)
spotify.playback_start_tracks([t.id for t in tracks.items])

**Comment by felix-hilden** [comment]
Hi! Could you clarify a bit? Your issue title states "invalid URI" but the error described is "URL contains no code" which seems like it's related to authorisation instead.

**Comment by Abdulsamipy** [comment]
```
redirect_uri = "spotify:track:52xJxFP6TqMuO4Yt0eOkMz"

conf = (client_id, client_secret, redirect_uri)
```

as  you can see in the code i added the redirect_uri as mentioned in the example code, but when i am running it, it is giving 

"KeyError: 'Passed URL contains no parameter code!'"

and on google i am getting Invalid redirect_uri

**Comment by felix-hilden** [comment]
Could you use a simpler call to verify that the authorisation succeeded?

```python
print(spotify.current_user())
```
for example.

**Comment by Abdulsamipy** [comment]
```
Opening browser for Spotify login...
Please paste redirect URL:  spotify:track:52xJxFP6TqMuO4Yt0eOkMz
Traceback (most recent call last):
  File "c:\Users\abdul\Desktop\Codes\Spotify\TEKNOT\test.py", line 8, in <module>
    token = tk.prompt_for_user_token(*conf, scope=tk.scope.every)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tekore\_auth\util.py", line 248, in prompt_for_user_token
    return auth.request_token(url=redirected)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tekore\_auth\util.py", line 170, in request_token
    code = parse_code_from_url(url)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tekore\_auth\util.py", line 47, in parse_code_from_url
    return _parse_url_param(url, 'code')
  File "C:\ProgramData\Anaconda3\lib\site-packages\tekore\_auth\util.py", line 26, in _parse_url_param
    raise KeyError(f'Passed URL contains no parameter `{param}`!')
KeyError: 'Passed URL contains no parameter `code`!'
PS C:\Users\abdul\Desktop\Codes\Spotify\TEKNOT> 
```

**Comment by felix-hilden** [comment]
Yep, so as you can see, the problem is in `prompt_for_user_token`. What are you pasting in?

**Comment by Abdulsamipy** [comment]
i am passing the following values:
```

client_id = "ID_FROM_DEV_SPOTIFY"
client_secret = "SECRET_FROM_DEV_SPOTIFY"
redirect_uri = "spotify:track:52xJxFP6TqMuO4Yt0eOkMz"

conf = (client_id, client_secret, redirect_uri)
```

**Comment by felix-hilden** [comment]
I mean when the function asks for your website URL after authorising Spotify. It doesn't have a `code` parameter. Did you follow the proper [procedure](https://tekore.readthedocs.io/en/stable/getting_started.html#retrieving-a-user-token)?

**Comment by felix-hilden** [comment]
Oh no, I might've overlooked the simplest thing. `redirect_uri` is a track URI, not a valid auth URI. Please change that to be the appropriate value to your application.

**Comment by Abdulsamipy** [comment]
okay, thank you , is there is a way to run it without application?

**Comment by felix-hilden** [comment]
I'm afraid not, Spotify wants to control access to the API. Let me know if you run into any issues!

**Comment by tomer-mil** [comment]
I'm having the exact same problem and I have tried two different ways. The first one, simply calling the `prompt_for_user_token` method and pasting the redirect URI as required (and i'm certain that it's the exact same URI as the whitelisted one) and I get back the error Abdulsamipy got. Second way was copying the authentication server I found in the tekore docs, and again no luck either. Any thoughts?

**Comment by felix-hilden** [comment]
Thank you for finding this issue instead of filing a new one! I'd guess the problem is some small overlooked detail, since nobody else has reported problems. We could have a closer look together if you care to join our Discord server (readme), it's a lot more informal!
