### ISSUE TITLE
Fast gathering of async results

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/tekore#271]
@Crussader figured out a neat way of fetching a bunch of async results using `asyncio.gather`. We could revise the documentation to reflect the fact that our builtin convenience methods don't produce the absolute quickest results and present this instead.

**Comment by Crussader** [comment]
`asyncio.gather` should speed up fetching results from 30-35 seconds down to 1.5-2* for a 10k Spotify Playlist. This definitely can get ratelimited after first one-two times its done, but this is used for testing purposes. So, in your use case you most likely wont be requiring that much data that quickly.

Note: This same logic can be used acorss other paginating API calls. Which in general should make your application faster without the need for Threading or caching but that is completely up to you.

**Comment by felix-hilden** [comment]
Yeah we have to be pretty careful of not promising any consistent speedups, so I worded the examples above to say that it is for quick, infrequent bursts of calls and decreases delays for larger workloads.
