### ISSUE TITLE
Support for the new Spotify Links

### ISSUE THREAD

**Issue by SimplyKitter** [felix-hilden/tekore#301]
Soo, spotify has been providing mobile users with a **spotify.link** domain and a random ID at the back instead of using the standard open.spotify.com for both Playlists and Tracks.

Examples:
![image](https://github.com/felix-hilden/tekore/assets/87762092/ebfebd55-d820-47f6-9210-f6a82cde4fcc)
![image](https://github.com/felix-hilden/tekore/assets/87762092/0358082b-2d76-4617-ac46-d3924e020e4c)

Adding support for this would be beneficial for most users here 🙏🙏

**Comment by felix-hilden** [comment]
Oh! Thanks for letting me know! Contributions are welcome but if not, I'll try to get it done within a few days 👍

**Comment by felix-hilden** [comment]
Okay, so unfortunately as you said, the IDs are random so we can't decide what it contains. I'll provide a function like `is_spotify_id` and possibly a HTTP call to try to resolve the redirect. But these might need to wait since Spotify doesn't have any docs about this ☹️

**Comment by SimplyKitter** [comment]
Oo, alrighty. Thanks for taking your time into this!!

**Comment by SimplyKitter** [comment]
I just found a workaround for this which works, uses requests to get the final open.spotify.com/ url

https://community.spotify.com/t5/Spotify-for-Developers/Give-us-an-endpoint-to-decode-new-shortened-share-links/m-p/5637302/highlight/true#M10762

**Comment by SimplyKitter** [comment]
I guess.. Thanks again though!

**Comment by felix-hilden** [comment]
Alright I had a go at it and it looks promising. There's some hoops to go through since this is a new type of URL, but I think we can add it directly to the client which is way more usable. Unfortunately my weekend is busy, but I'll let post any updates on this issue 👍

**Comment by felix-hilden** [comment]
Hi! I've got a PR up now, which I'd really appreciate comments on. Does it seem usable for what you had in mind for whatever app you intended to write?

**Comment by SimplyKitter** [comment]
I will test it later today, will let you know!
