### ISSUE TITLE
Pydantic v2.5.0 breaks unions

### ISSUE THREAD

**Issue by HarrySky** [felix-hilden/tekore#306]
Hi,  I updated my service this evening and encountered following problem

### Issue
It started to throw Pydantic validation errors when it fetches currently playing song, because, according to logs, it thinks that it is `LocalTrack` instead of `FullTrack`

### Expected behavior
It should recognise that FullTrack is playing, but Pydantic changed the way unions are processed in v2.5.0

### Steps to reproduce
You need to call `api.playback_currently_playing()` with your account when some non-local track is playing

P.S. Thank you for your continuous work on this great library :cowboy_hat_face:

**Comment by felix-hilden** [comment]
Oh wow, okay I'll try to address it tomorrow. Thanks for letting me know and for the kind words 😄 I'm happy to see you still getting something out of it!

**Comment by HarrySky** [comment]
Thanks, temporary fix I use is to pin Pydantic to 2.4.2 in my requirements.txt

**Comment by felix-hilden** [comment]
Okay this seems to be deeper than I can resolve, so I opened pydantic/pydantic#8119. Let's see what they know!

**Comment by felix-hilden** [comment]
Alright it was their bug! I'll wait for the fix release, disallow 2.5-2.5.1 and then release a fix version, but just by upgrading Pydantic everything should be fine
