### ISSUE TITLE
Missing tag for 5.3.0

### ISSUE THREAD

**Issue by mgorny** [felix-hilden/tekore#314]
The tag for 5.3.0 hasn't been pushed to this git repository. Could you push it, please? We're using tags to fetch the sources along with tests.

**Comment by felix-hilden** [comment]
Ah thanks! I was doing this in the midst of holiday packing and forgot, also important to have the stable docs up to date!

Just for curiosity, what are you testing? Tekore as a type of source dist from Github?

**Comment by mgorny** [comment]
I meant running the test suite when packaging tekore for Gentoo.
