### ISSUE TITLE
Git flow and release pipeline

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/tekore#43]
What should be the way to release the package and its documentation?

In terms of branching, the releases could be implemented as tags. This way the master branch can be used as the default branch, not just the latest published version. Then tests would be run and documentation build verified on every merge. Releases to PyPI and RTD would be done by hand when the version is deemed ready. If the project grows, a separate development branch could be used. And if different configurations could be used in Travis, the master branch build could automatically publish the new version.

Not sure yet. Thoughts, anyone?

**Comment by marioortizmanero** [comment]
I honestly always prefer to keep the main branch clean of WIP, specially because the documentation may change and new users seeing the API for the first time may be confused after reading documentation for an unreleased version, so I agree with you. I also prefer manual releases, they feel more safe to me.

**Comment by felix-hilden** [comment]
That's a good point, maybe a dev branch could be created on the first release. There shouldn't be any WIP in the main branches anyway, but I agree it could be confusing for new visitors to see a different state than on PyPI.

I'll look at what would be the best way to build with Travis using multiple branches, if it's different at all. Then I guess the main branch could be dev, no commits or merges would be made to master, and master would rebase onto dev on every release. But I'll have to study git some more to confirm this flow, so no accidents happen :D

**Comment by felix-hilden** [comment]
Git flow verified, and if we use manual releases Travis doesn't need to be changed. For test coverage it could be worth it to point Code Climate to dev. Measuring only on release would lag behind too much. I'll close this issue on first release after creating the dev branch.

**Comment by felix-hilden** [comment]
Another problem came to mind. The API evolves constantly, and I've already been burned by undocumented response attributes and changing responses. Suppose we publish version 3.0. Shortly after the API is changed ever so slightly, but our dev branch has already progressed and we'd like to wait before a release. So committing the fix to dev won't do. We'll follow a hotfix flow as laid out [here](http://www.inanzzz.com/index.php/post/9qea/working-with-git-hotfix-branches).

**Comment by felix-hilden** [comment]
Dev branch created!

**Comment by felix-hilden** [comment]
When I thought about it more, a dev branch suits bigger projects well, but I expect big features (like the recently opened Async issue) to already be in separate branches until merged. So Dev would be somewhat superfluous. Let's keep the releases frequent and master off WIP and we'll be fine. Then if this project gets out of hand we might reconsider.
