### ISSUE TITLE
Different readmes for GitHub, PyPI and RTD

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/tekore#54]
Duplicating information is no good, and it leads to harder-to-maintain documentation. Having the most relevant information in correct places and linking between them could be a better strategy than just having one readme for all services surrounding the package.

Here's what I'm currently at. Each readme would include a short section with general information. It would be pretty much the same for every document. It would introduce spotipy and link to other services. It could also include a short example snippet of code. Then every readme would have some service-specific information.

#### GitHub
- Cloning the repository
- Running tests
- Building documentation
- Contributing

#### Read The Docs
- Features
- Getting started (with the Web API application as well)
- Documentation structure

#### PyPI
- Package info and history (all the relevant information regarding previous versions)
- How to install (possibly using different methods along with pip)

Maybe something else too.

**Comment by felix-hilden** [comment]
Waiting for transfer on PyPI and RTD for hyperlinks to be valid.

**Comment by SHxKM** [comment]
Has this occurred yet? any chance to see a `readthedocs` documentation site soon? Huge props for doing this!

**Comment by marioortizmanero** [comment]
Here's the issue where Felix requested the readthedocs site: https://github.com/readthedocs/readthedocs.org/issues/6335

It should be resolved after Dec 19th, so there's still a bit left. PyPi support seems to be a bit stuck too: https://github.com/pypa/pypi-support/issues/28

**Comment by felix-hilden** [comment]
@SHxKM Sadly no, as Mario pointed out. But do build the documentation yourself, it's a good resource! Have a look at the github readme for instructions if you didn't do it already.

**Comment by SHxKM** [comment]
Hmm, aren’t there many merits to just shipping this as a different package?

**Comment by felix-hilden** [comment]
Have a look at #22 and voice your opinion, I'd love to hear your thoughts as well. The discussion on that topic starts [here](https://github.com/felix-hilden/spotipy/issues/22#issuecomment-545127947).

**Comment by felix-hilden** [comment]
@SHxKM There is a temporary [RTD site](https://updated-spotipy-test.readthedocs.io/en/latest/) available now!

I also committed a future PyPI readme. Now the only thing left to do is update links when the name transfer issue is resolved.

**Comment by felix-hilden** [comment]
The initial release to PyPI has now been made and its readme is available there, I'll close this issue.
