### ISSUE TITLE
What should be importable from the top level

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/tekore#81]
It would be convenient for users to be able to import things straight from the `spotipy` level instead of submodules. What should be importable that way?

Currently the imports are:
- auth: Token, Credentials
- scope: Scope, scopes
- client: Spotify

I see two approaches, make only the bare necessities importable or make everything that is useful to the user importable. The bare necessities would in my opinion only involve Credentials and Spotify, as they enable retrieving a token and calling the API. Everything useful for the user would include:
- client: Spotify
- model: none from here
- auth: Credentials
- convert: to and from URL and URI
- scope: Scope, scopes, read, write and every
- sender: all senders
- serialise: none from here
- util: read env, creds from env, prompt and refresh

But this could be confusing. In my opinion the better thing to do is just have Credentials and Spotify at the top level and have everything else in their modules. That way they would be grouped nicely.

**Comment by felix-hilden** [comment]
I think we'll do:
- auth: Credentials
- client: Spotify

**Comment by felix-hilden** [comment]
This issue could be revisited. Having access to every relevant function and type at the top level could be very beneficial. Currently, one has to remember both the location and the name of things, when only the name could be enough.

```python
# Currently - import modules
from tekore import util, Spotify
util.config_from_environment(...)
util.prompt_for_user_token(...)
Spotify(...)

# Currently - import explicitly
from tekore import Spotify
from tekore.util import config_from_environment, prompt_for_user_token
config_from_environment(...)
prompt_for_user_token(...)
Spotify(...)

# Could be
import tekore as tk
tk.config_from_environment(...)
tk.prompt_for_user_token(...)
tk.Spotify(...)
```

This could be a better way, but documentation could have to be changed a lot. Perhaps the module structure too, partly also because the `scope` module could be confused with the `scopes` enumeration.

**Comment by marioortizmanero** [comment]
I like the `tk` approach (although [a GUI toolkit has the same name](https://en.wikipedia.org/wiki/Tk_(software)) and might cause issues). I personally prefer the `numpy`-like approach, because most times one module requires another, so you end up having to import both of them. For instance, you always need `tekore.scope` when you use `tekore.utils.prompt_for_user_token`, and such. Specially the `auth` and `scope` modules.

**Comment by felix-hilden** [comment]
Yup, I kinda agree. And I don't mind the `tk` name clash. It could be abbreviated with `t` or anything. But we should figure out whether the modules would need renaming. In that case they would just be traps to fall into, not intended places to import things from. We ought to make a suggestion of the changes here before going further. I'll see to it.

**Comment by felix-hilden** [comment]
These could be the changes we do:

- `auth`:
  * rename to `_auth`
  * import credential clients at the top level
- `client`
  * rename to `_client`
  * import client at the top level
- `convert`
  * rename to `_convert` and import at top level OR leave as it is
- `model`
  * rename to `_model`
- `scope`
  * rename to `_scope`
  * import everything at the top level
- `sender`
  * rename to `_sender` and import at top level OR leave as it is
- `serialise` removed in #149

How options are set need to be addressed. Variable names from which configuration is read are now in `tk.util.config.xxxx_var`. Default senders and send keywords are in `tk.sender.default_xxxx`.

`convert` and `sender` could be left as they are because they contain things that one wouldn't necessarily need all the time. Perhaps analoguous to `np.linalg.norm`. Plus, that would help in setting default senders as planned in #140.

Scopes will have some problems. What is `tk.every`? Ideally, I'd want to write: `tk.scopes.scope_name` and `tk.scopes.every`. That would require some changes though. While we're at it, users have no business knowing about the `Scope` object. The natural way to get a long list of scopes would be a sum, or accepting a list.

**Comment by felix-hilden** [comment]
One approach that could help setting options is late importing. For any function that uses options it could import from the top level namespace inside the function. That way the initial imports are not circular.

We have options now for setting the names of environment variables and setting default senders and their arguments. Neither of those tasks should really be so common that performance would be an issue. That would allow us to name and structure the private modules in any way we like.

**Comment by felix-hilden** [comment]
This change can be introduced gradually. We can provide the new imports already and at least include a notice in the documentation that this is about to change. Then in 2.0 we can restructure the modules and deny imports below the top level.

**Comment by felix-hilden** [comment]
Let's have every module as private, with the exception of `model`. And let's have `model` be just a shallow import layer for a private `_model`. Models aren't really supposed to be used, but if someone for some reason wants to import them for, say, type checking, we could provide a way to do it.

**Comment by felix-hilden** [comment]
I found that moving options to the top level is a good idea. Also, the scope enumeration should contain the special scopes as well, and lists of scopes should be accepted by authentication methods.
